### ISSUE TITLE
My AnyPoint Code Builder Instance is corrupted

### ISSUE THREAD

**Issue by tseanard** [mulesoft/docs-code-builder#124]
The mulesoft extensions are not loading and it just spins and spins..

![image](https://github.com/mulesoft/docs-code-builder/assets/3173923/159f93ea-3ed0-4023-b94e-0644ef2f89ea)

**Comment by dinglezos-2022** [comment]
Check any browser plugins you might have, that stop cookies and disable them. 
Sometimes blocked cookies are enough to stop a web based app working.
Alternatively try a Incognito/Private window.

**Comment by dukesphere** [comment]
Hi @tseanard, Thank you for providing feedback. If you are still experiencing this issue, please see https://docs.mulesoft.com/anypoint-code-builder/#feedback to provide feedback. If you are currently a customer, report issues through the [MuleSoft Help site](https://help.mulesoft.com/s/). You can also review the release notes for known issues and workarounds: https://docs.mulesoft.com/anypoint-code-builder/acb-release-notes  

The issues reported in this repo are intended for documentation issues only.
