### ISSUE TITLE
add support for linux platform (I can't use the extension with vscode for linux)

### ISSUE THREAD

**Issue by aslukili** [mulesoft/docs-code-builder#172]
many developers use a linux distro as their main operating system, therefore, it's necessary to support this users

**Comment by dukesphere** [comment]
Hi, @aslukili, Thanks for asking. Currenly, only Mac and Windows are supported for the desktop IDE. Please see https://docs.mulesoft.com/anypoint-code-builder/acb-release-notes#compatibility. 

To provide product feedback, please see https://docs.mulesoft.com/anypoint-code-builder/#feedback
