### ISSUE TITLE
Failure to import into VIsual studio code related to no release version

### ISSUE THREAD

**Issue by dinglezos-2022** [mulesoft/docs-code-builder#189]
I get the following error : 

"Cant install release version of 'salesforce.mule-dx-extension-pack' extension because it has no release version."

![visual studio anypoint extensions error](https://github.com/mulesoft/docs-code-builder/assets/95032934/8641d312-fe9a-40b9-b1ab-218c6cecd43b)

**Comment by valon-loshaj** [comment]
Getting the same error message when trying to download on Mac :(

**Comment by macrocks** [comment]
@dinglezos-2022 @valon-loshaj  GA release is available on Windows,Mac, Linux machines and there is no version issue on it.
Please try again n let us know.

**Comment by dukesphere** [comment]
Hi @dinglezos-2022 , As @macrocks says, you can now download the GA version on Mac and Windows. Linux is not supported at this time (see https://docs.mulesoft.com/release-notes/code-builder/acb-release-notes#compatibility).

To install the extensions for the desktop IDE, see https://docs.mulesoft.com/anypoint-code-builder/start-acb.

**Comment by dinglezos-2022** [comment]
Awesome, thank you @dukesphere ! I will try it out!
