### ISSUE TITLE
How to import existing MuleSoft application.

### ISSUE THREAD

**Issue by ypradeepkumar** [mulesoft/docs-code-builder#213]
Hi Team,

I am already working in Anypoint studio. How can I import those applications into Anypoint Code Builder???

**Comment by macrocks** [comment]
@ypradeepkumar  that feature is available on DESKTOP anypoint code builder IDE. Anypoint code builder cloud version cannot have connectivity to your desktop or any other file system so you cannot import your existing application.
for Desktop IDE import- refer this page
https://docs.mulesoft.com/anypoint-code-builder/upload-a-project

**Comment by macrocks** [comment]
@ypradeepkumar  - click on package explorer and you will be able to view EC2 folder struture there then select folder or folder ounder your username and then drag n drop folder u want to import
You can find documentation on https://docs.mulesoft.com/anypoint-code-builder/int-import-mule-project 
Please close this ticket as there is no more action required.

**Comment by dukesphere** [comment]
Hi, @ypradeepkumar Please do see the second link that @macrocks sent. And thank you @macrocks for responding. 

If you have further questions, please feel free to submit another issue.
