### ISSUE TITLE
W-15585467: APIKit Console not present when we run application on ACB

### ISSUE THREAD

**Issue by youpracticewithme** [mulesoft/docs-code-builder#295]
Hello Team,

I did implmented API specification on ACB using Implement API specification option. It has imported API specification n created HTTP listener configuration along with enabled console option as well.

When I run application, it ran successfully on local machine and API Console is exposed on http://localhost:8081/console endpoint and I can access it on browser as well.

In Anypoint studio, whenever we run such application, be default it opens apikit console on bottom window, can we have the feature available on ACB as well.

<img width="947" alt="image" src="https://github.com/mulesoft/docs-code-builder/assets/129696961/f4d1d882-d470-4704-b611-7a97d21658ee">

**Comment by simoneegeib** [comment]
Thanks you for your message and for your suggestion of an enhancement.
We are currently not planning to port the APIkit console to ACB. It's very easy to use a VS Code extension like thunderclient for API testing

**Comment by dukesphere** [comment]
Thanks for your suggestion. Please see our response above from simoneegeib, @youpracticewithme
