### ISSUE TITLE
Link to mq-queues.adoc#create-a-queue doesn't work

### ISSUE THREAD

**Issue by hannanelson** [mulesoft/docs-code-builder#367]
This xref needs the mq repo to resolve correctly:
`xref:mq-queues.adoc#create-a-queue[Create a Queue]
`
https://github.com/mulesoft/docs-code-builder/blob/162cd434ad8d33900d75bd58103ddeb1f33c2fce/modules/ROOT/pages/imp-asyncapi.adoc?plain=1#L355

**Comment by chris-campbell9** [comment]
PR: https://github.com/mulesoft/docs-code-builder/pull/371

**Comment by chris-campbell9** [comment]
Fixed in the above PR. I'll close this issue.
